# -*- coding: utf-8 -*-
"""Лаба 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYJekrNSfa0NbgO5LxDAc3iMR9Bak9Nd
"""

#1
n=int(input())
if n==1:
   print('yanvar')
if n==2:
   print('fevral')
if n==3:
   print('mart')
if n==4:
   print('aprel')
if n==5:
   print('may')
if n==6:
   print('iyn')
if n==7:
   print('iyl')
if n==8:
   print('aygyst')
if n==9:
   print('setyabr')
if n==10:
   print('oktabr')
if n==11:
   print('noyabr')
if n==12:
   print('dekabr')

#2
n=int(input())
a=n%2
if a==1:
   print('nechet')
else:
  print('chet')

#3
n=int(input())
if n>40:
  print('stonks')
elif n<40:
  print('not stonks')
else:
  print('net v yslovii')

#4
n=int(input())
a=n%4
if a==0:
  print('True')
else:
  print('False')

#5
n=int(input())
a=n%2
b=n%3
c=n%5
if a>0 and b>0 and c>0 and n!=2 and n!=3 and n!=5:
  print('true')
elif n==5 or n==3 or n==2:
  print('true')
else:
  print('false')

#6
import math
a=int(input())
b=int(input())
if (a/b)>=3.6:
  s=a
  a=b
  b=s
  print("a", a)
  print("b", b)
elif a>=((-138/2)**1.3) and a<=(math.fabs((((-69)/28)**5.1)*4)):
  s=a
  a=b
  b=s
  print("a", a)
  print("b", b)
else:
  print("end")

a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=int(input())
chet=0
otr=0
prom=0
if (a%2)==0:
  chet+=1
if (b%2)==0:
  chet+=1
if (c%2)==0:
  chet+=1
if (d%2)==0:
  chet+=1
if (e%2)==0:
  chet+=1
if a<0:
  otr+=1
if b<0:
  otr+=1
if c<0:
  otr+=1
if d<0:
  otr+=1
if e<0:
  otr+=1
if a==b or a==c or a==d or a==e or b==c or b==d or b==e or c==d or c==e or d==e:
  print("числа не уникальные")
else:
  print("числа уникальные")
if a>=(-256) and a<=(1024):
  prom+=1
if b>=(-256) and b<=(1024):
  prom+=1
if c>=(-256) and c<=(1024):
  prom+=1
if d>=(-256) and d<=(1024):
  prom+=1
if e>=(-256) and e<=(1024):
  prom+=1
print("Четных чисел",chet)
print("Отрицательных чисел", otr)
print("В промежутке лежит", prom)

#Задание повышенной сложности
a=int(input())
b=int(input())
c=int(input())
s=(((a)**2+(b)**3)/c+3)/4
if (s%2)==0:
  print("chet")
else:
  print("nechet")