# -*- coding: utf-8 -*-
"""Лаба 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdGDvuGPuOzEDhZ9A3VnDwY2ytSk9x6J
"""

#1
a=5
b=int(input())
s=a*b
print(s)

#2
a=int(input())
b=int(input())
s=(a+b)**2
print(s)

#3
a=15
b=10
c=int(input())
s=(a+b)/c
print(s)

#4
a=int(input())
b=int(input())
s=(a+b)**2
print(s)

#5
a=int(input())
b=int(input())
c=int(input())
P=a+b+c
p=P/2
s=(p*(p-a)*(p-b)*(p-c))**0.5
print(P,s)

#6
a=int(input())
b=int(input())
s=(((a)**3+14)/5)*b
print(s)

#7
a=int(input())
n=int(input())
s=(a**2)/n
print(s)

#8
a=float(input())
n=float(input())
s=a//n
print(s)
b=int(input())
c=int(input())
i=b*c
print(i)
l=int(input())
m=int(input())
p=l%m
print(p)



#Повышенной сложности
#1
n=int(input())
day=n//86400
chasi=n%86400//3600
minyti=n%86400%3600//60
print("day", day)
print("chasi", chasi)
print("minyti", minyti)
#2
j=n+n**2+n**3
print(j)